name: nawirni
description: "SHTIWY represents an ambitious vision for the future of
  AI-powered education."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  auto_route: ^11.1.0
  auto_route_generator: ^10.5.0
  build_runner: ^2.15.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  easy_localization: ^3.0.0
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.1.0
  flutter_screenutil: ^5.9.2
  get_it: ^9.2.1
  google_fonts: ^8.1.0
  lean_builder: ^0.1.10
  shared_preferences: ^2.2.2
  supabase_flutter: ^2.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - .env
